### ISSUE TITLE
Feature request: Add support to serving local static files

### ISSUE THREAD

**Issue by vimmerru** [DSRCorporation/express-generator#12]
For local file storage usually we need the way to serve local static files.

**Comment by MRJCrunch** [comment]
Already done. We have an [option to serve static files](https://github.com/DSRCorporation/express-generator/blob/master/generators/app/templates/app/libs/initializers/middlewares.js#L39)

**Comment by fxlrnrpt** [comment]
Closed with [Added initializers for middlewares](https://github.com/DSRCorporation/express-generator/commit/dd101de7d5a91258a199abb09a92d5a91c34168a)
