### ISSUE TITLE
Feature Request: YARN migration

### ISSUE THREAD

**Issue by fxlrnrpt** [DSRCorporation/express-generator#5]
Add YARN support instead of npm+npm-shrinkwrap. Justification: https://medium.com/work-market-engineering/adventures-with-npm-shrinkwrap-facebook-yarn-fc157b713ac4#.8hzwn4fnr

**Comment by vimmerru** [comment]
May be use yarn just as option?

**Comment by fxlrnrpt** [comment]
@vimmerru I'd like it to be a default option then
