### ISSUE TITLE
Bug: Npm page doesn't have link to Github

### ISSUE THREAD

**Issue by vimmerru** [DSRCorporation/express-generator#7]
I can't find the way how to go to Github page from npm page https://www.npmjs.com/package/generator-express-dsr

Also i suggest to check same issue for angular-generator project.

**Comment by fxlrnrpt** [comment]
@vimmerru [generator-angular-dsr](https://www.npmjs.com/package/generator-angular-dsr) has the link

**Comment by MRJCrunch** [comment]
Done
